In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("Customer Analysis.csv")
data

C:\Users\pc\AppData\Local\Temp\ipykernel_19948\645809277.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Customer Analysis.csv")

,order_id,order_date,status,item_id,sku,qty_ordered,price,value,discount_amount,total,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Discount_Percent
0,100354678,01/10/2020,received,574772,oasis_Oasis-064-36,21,89.9,1798.0,0.0,1798.0,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
1,100354678,01/10/2020,received,574774,Fantastic_FT-48,11,19.0,190.0,0.0,190.0,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
2,100354680,01/10/2020,complete,574777,mdeal_DMC-610-8,9,149.9,1199.2,0.0,1199.2,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
3,100354680,01/10/2020,complete,574779,oasis_Oasis-061-36,9,79.9,639.2,0.0,639.2,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
4,100367357,13/11/2020,received,595185,MEFNAR59C38B6CA08CD,2,99.9,99.9,0.0,99.9,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286387,100562365,30/09/2021,paid,905179,APPCHA5AF14939B8F8A,2,4419.9,4419.9,0.0,4419.9,...,613-87-0361,212-772-7404,Rushville,Yates,Rushville,NY,14544,Northeast,bklatham,0.0
286388,100562376,30/09/2021,cod,905191,MEFCOT5A8D1E973B886,2,39.9,39.9,0.0,39.9,...,101-02-1040,229-817-9451,Lawrenceville,Gwinnett,Lawrenceville,GA,30044,South,bmbrunetti,0.0
286389,100562383,30/09/2021,cod,905200,WOFVAL59D5EA84167F9-M,2,40.0,40.0,0.0,40.0,...,399-31-7238,252-414-8396,Durham,Durham,Durham,NC,27701,South,fngiusti,0.0
286390,100562384,30/09/2021,cod,905202,WOFNIG5B4D7EB0E9FDD-L,2,49.9,49.9,0.0,49.9,...,399-31-7238,252-414-8396,Durham,Durham,Durham,NC,27701,South,fngiusti,0.0
286391,100562386,30/09/2021,processing,905205,MATHUA5AF70A7D1E50A,2,3559.9,3559.9,0.0,3559.9,...,320-11-8748,423-276-2699,Knoxville,Knox,Knoxville,TN,37920,South,reschlosser,0.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          286392 non-null  object
 1   order_date        286392 non-null  object
 2   status            286392 non-null  object
 3   item_id           286392 non-null  int64
 4   sku               286392 non-null  object
 5   qty_ordered       286392 non-null  int64
 6   price             286392 non-null  float64
 7   value             286392 non-null  float64
 8   discount_amount   286392 non-null  float64
 9   total             286392 non-null  float64
 10  category          286392 non-null  object
 11  payment_method    286392 non-null  object
 12  bi_st             286392 non-null  object
 13  cust_id           286392 non-null  int64
 14  year              286392 non-null  int64
 15  month             286392 non-null  object
 16  ref_num           286392 non-null  int64
 17  Name Prefix       286392 non-null  object
 18  First Name        286392 non-null  object
 19  Middle Initial    286392 non-null  object
 20  Last Name         286392 non-null  object
 21  Gender            286392 non-null  object
 22  age               286392 non-null  int64
 23  full_name         286392 non-null  object
 24  E Mail            286392 non-null  object
 25  Customer Since    286392 non-null  object
 26  SSN               286392 non-null  object
 27  Phone No.         286392 non-null  object
 28  Place Name        286392 non-null  object
 29  County            286392 non-null  object
 30  City              286392 non-null  object
 31  State             286392 non-null  object
 32  Zip               286392 non-null  int64
 33  Region            286392 non-null  object
 34  User Name         286392 non-null  object
 35  Discount_Percent  286392 non-null  float64
dtypes: float64(5), int64(7), object(24)
memory usage: 78.7+ MB